#ifndef BSP_SYSTEM_WATCHDOG_H
#define BSP_SYSTEM_WATCHDOG_H

#include <stdint.h>

#define BSP_SYSTEM_WATCHDOG_PRESCALER_DIVIDER  32U
#define BSP_SYSTEM_WATCHDOG_RELOAD_VALUE      1999U

typedef enum
{
  BSP_SYSTEM_WATCHDOG_STATUS_NOT_RUN = 0,
  BSP_SYSTEM_WATCHDOG_STATUS_OK,
  BSP_SYSTEM_WATCHDOG_STATUS_NOT_INITIALIZED,
  BSP_SYSTEM_WATCHDOG_STATUS_HAL_ERROR,
  BSP_SYSTEM_WATCHDOG_STATUS_HAL_BUSY,
  BSP_SYSTEM_WATCHDOG_STATUS_HAL_TIMEOUT
} BSP_SystemWatchdogStatus_t;

BSP_SystemWatchdogStatus_t BSP_SystemWatchdog_Init(void);
BSP_SystemWatchdogStatus_t BSP_SystemWatchdog_Refresh(void);

#endif
